CachyOS/linux-cachyos

linux-bore/auto-cpu-optimization.sh
linux-bore/configure
linux-cachyos-bmq/auto-cpu-optimization.sh
linux-cachyos-bmq/configure
linux-cachyos-bore/auto-cpu-optimization.sh
linux-cachyos-bore/configure
linux-cachyos-cacule/auto-cpu-optimization.sh
linux-cachyos-cacule/configure
linux-cachyos-cfs/auto-cpu-optimization.sh
linux-cachyos-cfs/configure
linux-cachyos-hardened/auto-cpu-optimization.sh
linux-cachyos-hardened/configure
linux-cachyos-pds/auto-cpu-optimization.sh
linux-cachyos-pds/configure
linux-cachyos-rc/auto-cpu-optimization.sh
linux-cachyos-rc/configure
linux-cachyos-tt/auto-cpu-optimization.sh
linux-cachyos-tt/configure
linux-cachyos/auto-cpu-optimization.sh
linux-cachyos/configure
linux-cacule-rdb/auto-cpu-optimization.sh
linux-cacule/auto-cpu-optimization.sh
linux-cacule/configure
linux-tt/auto-cpu-optimization.sh
linux-tt/configure

This commit is specified for close a issue #22 this need a test.

Disable Specify configs for MIVYBRIDGE

---

README.md

... again. Honestly, is it really necessary to install this version of pacman with the repository add?

README: Fix the repository installation command

---

linux-bore/auto-cpu-optimization.sh
linux-cachyos-bmq/auto-cpu-optimization.sh
linux-cachyos-bore/auto-cpu-optimization.sh
linux-cachyos-cacule/auto-cpu-optimization.sh
linux-cachyos-cfs/auto-cpu-optimization.sh
linux-cachyos-hardened/auto-cpu-optimization.sh
linux-cachyos-pds/auto-cpu-optimization.sh
linux-cachyos-rc/auto-cpu-optimization.sh
linux-cachyos-tt/auto-cpu-optimization.sh
linux-cachyos/auto-cpu-optimization.sh
linux-cacule-rdb/auto-cpu-optimization.sh
linux-cacule/auto-cpu-optimization.sh
linux-tt/auto-cpu-optimization.sh

Hello, i opening that pull request because i work on the auto-cpu-optimization.sh for be more readable and more strong what i do:
- Put some controls for see if the users have installed GCC if not the script gonna print: `Error: GCC is not installed. Please install GCC and try again.`
- Converted the "IF" and "ELIF" to CASE
- Optimized the fuctions for get cpu type from gcc i do in only one. That fuction gonna pick the CPU TYPE from gcc and covert to uppercase and store to MARCH 
Best Regards,
NextWorks

rework the entire auto-cpu-optimization.sh

---

linux-bore/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-cacule/PKGBUILD
linux-cachyos-cfs/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-pds/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-tt/PKGBUILD
linux-cachyos/PKGBUILD
linux-cacule-rdb/PKGBUILD
linux-cacule/PKGBUILD
linux-tt/PKGBUILD

Cleaner and makes it easier to add new choices.
I would also like to do a similar refactoring for the other similar options.

Refactor condition of HZ ticks

---

linux-bore/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-cacule/PKGBUILD
linux-cachyos-cfs/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-pds/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos-tt/PKGBUILD
linux-cachyos/PKGBUILD
linux-cacule-rdb/PKGBUILD
linux-cacule/PKGBUILD
linux-tt/PKGBUILD

Notice:
- hardened is renamed to bore-hardened for clarity (well, there is no such scheduler as "hardened")
- Introduced a local `_die()` function to exit the build

Refactor condition of CPU sched

---

README.md

Your lovely writer strikes again! ;)

Refactor of schduler list

---

README.md

It will be more clear for a first look without precise reading and looks better and preserve all details.

Update of kernel features

---

README.md

- Changed the logical structure of docs
- Re-worked section for cachyos repositories - it should be much clearer to understand now
- Fix typo

Big update docs

---

linux-bore/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-cfs/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-pds/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos-tt/PKGBUILD
linux-cachyos/PKGBUILD
linux-tt/PKGBUILD

The build was successful, so I think it's OK. (https://github.com/ventureoo/linux-cachyos/actions/runs/4144396315).

Refactor build function

---

README.md

Adding a missing, ending backtick on L39.

chore(README.md): Add missing ending backtick

---

linux-bore/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-cfs/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-pds/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos-tt/PKGBUILD
linux-cachyos/PKGBUILD
linux-tt/PKGBUILD

Use built-in bash substitution for uppercase

---

linux-bore/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-cfs/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-pds/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos-tt/PKGBUILD
linux-cachyos/PKGBUILD
linux-tt/PKGBUILD

I prepared for the tests that @ptr1337 wants to run

Use zstd -19 for module compression

---

.github/workflows/lint.yml

Fixes LLVM build with Thin LTO for CI.

ci: Disable debug to lower size of kernel

---

linux-cachyos-rt/.SRCINFO
linux-cachyos-rt/PKGBUILD

linux-cachyos-rt: Fix localversion from RT patch

---

README.md

readme: update links to add repo

---

README.md

Update the description of the repository

6.6: Update README.md

---

README.md

As in the title - a small README update.

Update schedulers list && add info about scx-scheds-git

---

archive/linux-cachyos-bmq/PKGBUILD
archive/linux-cachyos-cfs/PKGBUILD
archive/linux-cachyos-pds/PKGBUILD
archive/linux-cachyos-tt/PKGBUILD
archive/linux-tt/PKGBUILD
linux-bore/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-rt/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

fix(hardcoded): fix hardcoded

---

linux-bore/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-rt/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos/PKGBUILD

This fixes clang from complaining about unsupported flags.

Fix LTO&kCFI

---

linux-bore/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-rt/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

As requested by @vnepogodin, the implementation of the "-n" flag

-lto suffix rework

---

linux-bore/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-echo/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-sched-ext-debug/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

Fixes: https://github.com/CachyOS/linux-cachyos/issues/257

Fix incorrect _processor_opt handling for x86-64 levels

---

linux-cachyos-rc/PKGBUILD

Please merge it after confirming that it builds.

linux-cachyos-rc: Build NVIDIA closed again

---

linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

Likely, the author meant "AND" operation

Correct logical operation for RT kernels

---

README.md

Hi, the mirrorlist for znver4 and v4 are the same, right?

README: Fix znver4 mirrorlist and add core/extra
