CachyOS/linux-cachyos

linux-bore/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-cacule/PKGBUILD
linux-cachyos-cfs/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-pds/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-tt/PKGBUILD
linux-cachyos/PKGBUILD
linux-cacule-rdb/PKGBUILD
linux-cacule/PKGBUILD
linux-tt/PKGBUILD

Zhe "zfs-meta" will be added with 6.1.9 and further. As soon these Kernels are in the repo it will be also added to the cachyos installer
Signed-off-by: Peter Jung <admin@ptr1337.dev>

Add ZFS-MODULE provides at linux-cachyos-*-zfs package

---

.github/workflows/lint.yml

Fixes: https://github.com/CachyOS/linux-cachyos/pull/72

ci: Move the pkgbuild-action fork to CachyOS

---

.github/workflows/lint.yml
linux-bore/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-cfs/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-pds/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos-tt/PKGBUILD
linux-cachyos/PKGBUILD
linux-tt/PKGBUILD

Unfortunately, I also had to disable LTO for LLVM because even with `_use_llvm_lto=thin` it takes up too much space.
Fixes: https://github.com/CachyOS/linux-cachyos/issues/119

Add use of the -Os flag in CI

---

linux-bore/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-cfs/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-pds/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos-tt/PKGBUILD
linux-cachyos/PKGBUILD
linux-tt/PKGBUILD

In the previous pull request (#124), we added the changes made by Arch Linux. Therefore, the use of this flag no longer makes sense.

Drop zstd compression flag

---

linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD

Applying the same changes in the 6.1 kernel as in the 6.4 kernel - equivalent to PR #124 and #128. In addition, removing the ZRAM/ZSWAP compression flag - as was done in commit e86620352ec731b573490e337da6bd00404fb94a

Adaptation of LTS kernels to the changes used in kernel 6.4

---

.github/workflows/lint.yml
linux-bore/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-cfs/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-pds/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos-tt/PKGBUILD
linux-cachyos/PKGBUILD
linux-tt/PKGBUILD
script.sh

Similar to ZFS, this allows us to build an NVIDIA driver module already purpose-built for our kernel. This will allow us to save NVIDIA driver users from constant rebuilding of dkms modules, which is often accompanied by a number of errors.
Note that in PKGBUILD, we will probably need to update ``_nv_ver`` whenever we update the driver itself, so that there is no mismatch in the versions of modules and nvidia-utils in our repository.
Also, note that I did not test the build together with LLVM+LTO, so this may require additional testing/fixes.

Add support for NVIDIA module build

---

linux-bore/PKGBUILD
linux-cachyos-bore-rt/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

We can remove our workaround: https://github.com/CachyOS/linux-cachyos/issues/152

Revert: Prevent ZFS and bcachefs building at the same time (issue #152 is solved now)

---

linux-bore/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-rt/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

If we will add [sched-ext-latest](https://github.com/CachyOS/kernel-patches/blob/master/6.6/sched/0001-sched-ext-latest.patch) to linux-cachyos, we just need to merge this pull request.

6.6 Add scx_layered && set alphabetical order in sched-ext-schedulers package

---

linux-bore/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-rt/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

Since we ship fbdev=1 by default in cachyos-settings, we need to apply this patch to fix system boot issues.
See: https://forums.developer.nvidia.com/t/545-29-06-18-1-flip-event-timeout-error-on-startup-shutdown-and-sometimes-suspend-wayland-unusable/274788/20

Add fbdev=1 fix for NVIDIA module

---

README.md

Hi.
I am one of the maintainers of the Fedora version (https://github.com/sirlucjan/copr-linux-cachyos) of the CachyOS kernel. I would like to update the README for Fedora, so we have one place (namely the COPR page) for the installation instructions, thereby avoiding outdated instructions and confusion among the users.
Thank you.

Update README for Fedora

---

linux-bore/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-rt/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

Until we solve the problems with BORE, it would be good to standardize the flags  (https://github.com/CachyOS/linux-cachyos/commit/8e0150f5955f7b132fa04e7e55caa8528fc31a89)

6.7: Update cpu scheduler flags

---

linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-echo/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

refactor modules dir to use version file generated by kernel makefile
that way we use whatever kernel generated for the modules dir name, rather than guessing the name of the kernel modules ourselfs

fix: refactor modules dir to use version file

---

linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-echo/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

When building inside tmpfs, ``$srcdir`` and ``$pkgdir``, their parent directory will not be the directory with PKGBUILD, but /tmp. So we need to read symlink of one of the files in ``$srcdir`` to figure out where the directory with PKGBUILD actually is.

Fix config saving when building inside tmpfs

---

linux-cachyos-bore/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

Confirmed working on 6.11 LTO kernel with nvidia-dkms.

6.11: Fix fbdev for NVIDIA closed modules

---

linux-cachyos-bmq/.SRCINFO
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/.SRCINFO
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/.SRCINFO
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/.SRCINFO
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/.SRCINFO
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/.SRCINFO
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-sched-ext/.SRCINFO
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/.SRCINFO
linux-cachyos-server/PKGBUILD
linux-cachyos/.SRCINFO
linux-cachyos/PKGBUILD

The first part of #286.
We should roll this out to all the LTO kernels first for about a week or two. After that period, we can move on to the 2nd part that is using clang/ThinLTO for the default kernel.

Add patch to workaround incompatible dkms modules when building with clang

---

linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

Currently, we set the `min_base_slice_ns` value of BORE to 1000000 (1ms). This was previously added to circumvent some audio crackling and glitches
using 1000Hz kernel. However, a few benchmarks I did (see below) shows that throughput is worse with a base slice of 1ms compared to 2ms.
This behaviour is expected and it doesn't matter much when using BORE as a scheduler because we are not focused on throughput, but rather deskop responsiveness
and interactivity. What was unforeseen however, was the fact that responsiveness under heavy load was also hurt by lowering the base slice to 1ms. 
@firelzrd, the developer of BORE, has also stated that a base slice of anything lower than 2ms will cause excessive scheduling, poor cache efficiency and
increased CPU overhead. It will also lower …

BORE: Restore default base slice value of 2ms

---

linux-cachyos/.SRCINFO
linux-cachyos/PKGBUILD
linux-cachyos/linux-cachyos.install
script-v3-v4.sh

Second and final part of #286. The default kernel will now use clang + ThinLTO as its default configuration.
To accomodate this change, I have added a conditional statement for each `_package` function to replace existing LTO kernels that are already installed to smoothen the transition. Furthermore, I have modified the build script to ensure that all PKGBUILDs will build with GCC first before building the LTO kernels.
We should do a staged rollout for this change to cachyos-testing-v3 -> cachyos-znver4 -> all repos to ensure that everything works correctly (most notably dkms modules, even though they compile successfully, we should ensure complete functionality)
Closes #286

linux-cachyos: Default to ThinLTO

---

linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

This syncs all PKGBUILDs to the recent change made in https://github.com/CachyOS/linux-cachyos/commit/334ab6e62fa06a83a920070b462dc247a7924882. Functionality is kept the same for all other kernels.
Also fixes a typo made in the aforementioned commit.

PKGBUILD: Add $use_gcc_suffix

---

linux-cachyos/.SRCINFO
linux-cachyos/PKGBUILD

6.11.4 is just around the corner now and LTO kernel users should have migrated packages already. We can safely remove this check now to keep the PKGBUILD clean and not break .SRCINFO

linux-cachyos: Remove `_is_lto_kernel` checks

---

linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-sched-ext/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

I have noticed today, when compiling the AutoFDO Kernel that the compression was pretty slow.
When adding T0 the compression is speed up and reduces the build time. Since we do not need to care yet about reproducible , this is fine to set

Modules: Use all available threads for compressing the modules

---

linux-cachyos-autofdo/PKGBUILD
linux-cachyos-rc/PKGBUILD

This enables the possibility of using AutoFDO without explicitly enabling Thin/Full LTO.

linux-cachyos-autofdo: Add clang check when $_autofdo* is enabled

---

linux-cachyos-autofdo/PKGBUILD
linux-cachyos-rc/.SRCINFO
linux-cachyos-rc/PKGBUILD

Depends on https://github.com/CachyOS/kernel-patches/pull/80

6.12: Sync nvidia patches

---

linux-cachyos-autofdo/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

6.12 includes sched-ext, so we need to update dependencies

6.12: Add scx-scheds as optdepend

---

linux-cachyos-autofdo/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-rt-bore/.SRCINFO
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

RT patch was removed in [this commit](https://github.com/CachyOS/linux-cachyos/commit/503f4835a29d4ea7925a5fd82344a553915091e1#diff-937eef1bb8b2c79262b3ed3c17a7cf230a3ca7677752f88c88c819df1e7b28c9L251), but there are still some patches in the RT patch set that have not yet been merged, such as the one that makes i915 compatible with PREEMPT_RT.

Revert RT patch deletion

---

linux-cachyos-autofdo/PKGBUILD
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos/PKGBUILD

BBR relies on pacing that is currently only implemented on fq[1]. While this is not mandatory since [2], research[3][4][5][6] has shown that fq is still preferable to use, not only on BBR but also as a general packet scheduler on host systems. With that in mind, we can adopt using fq as the default globally in our config instead, but since this requires further consideration, let's just set this when BBR is enabled for now.
This is not set on the server kernel where using fq_codel seems to be more desirable.
[1] https://man7.org/linux/man-pages/man8/tc-fq.8.html
[2] https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=218af599fa635b107cfe10acf3249c4dfe5e4123
[3] https://research.cec.sc.edu/files/cyberinfra/files/BBR%20-%20Fundamentals%20and%20Updates%202023-08-29. …

feat: Use fq packet scheduler when BBR is enabled

---

linux-cachyos-bmq/auto-cpu-optimization.sh
linux-cachyos-bore/auto-cpu-optimization.sh
linux-cachyos-deckify/auto-cpu-optimization.sh
linux-cachyos-eevdf/auto-cpu-optimization.sh
linux-cachyos-hardened/auto-cpu-optimization.sh
linux-cachyos-lts/auto-cpu-optimization.sh
linux-cachyos-rc/auto-cpu-optimization.sh
linux-cachyos-rt-bore/auto-cpu-optimization.sh
linux-cachyos-server/auto-cpu-optimization.sh
linux-cachyos/auto-cpu-optimization.sh

Adds some missing arches, syncing with the patches.
I know some of the new cases can be omitted, using the default fallthrough+uppercase codepath, but this was easier to do with a single sed command.

Sync arches

---

linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-rc/.SRCINFO
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/.SRCINFO
linux-cachyos/PKGBUILD

Since we are compiling the default kernel with clang rather than GCC, we need to pull clang as a dependency
to ensure functionality with building out-of-tree kernel modules. For CachyOS users, this is already seamless
because our dkms package is dependent on clang, but AUR users and non-CachyOS users can suffer from this.
Note that this generates a bogus .SRCINFO when !_is_clang_kernel() but that doesn't matter for 100% of usecases
because it's default True (unless some third party repository defaults to GCC in which case they should fix it
on their own).
Depends on #354

linux-cachyos{,-rc}: Conditionally add clang-llvm to headers dependencies

---

linux-cachyos-rc/PKGBUILD

This adds fixes for nvidia-drm.fbdev in 6.13 and finally enables support for the prebuilt closed module.
Patches are based on the latest HEAD of [1] at the time of writing. Patches have also been pushed to the `staging` branch of [2] and will be merged in tandem with this PR.
[1] https://github.com/CachyOS/open-gpu-kernel-modules/tree/565-cachyos
[2] https://github.com/CachyOS/kernel-patches/

linux-cachyos-rc: Update NVIDIA patches

---

linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD
script-v3-v4.sh
script-znver4.sh
script.sh

It allows to get rid of duplicating the variable name, which helps to avoid typical typo errors and looks prettier.

Refactor setting of default values

---

linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

We've talked about this before in https://github.com/CachyOS/linux-cachyos/issues/367, and this time I've limited myself to removing options that won't cause doubt.
First commit removes `_makegconfig` and `_makemenuconfig`:
> 
> We have 4 interfaces for kernel configuration, most of which have the
> same functionality and differ only in the rendering backend. gconfig
> uses GTK2 which is EOL, and unlikely anyone will install it just for
> gconfig when there are alternatives like xconfig which is based on Qt5 /
> Qt 6. Similarly in the case of TUI, instead of menuconfig, here we have
> ncurses based nconfig which is supported by most terminals.
Second commit removes `_NUMAdisable`:
> 
> The first reports of positive impact of disabling NUMA for desktop
> systems date back to 2012 [1], and …

Cleanup options (part 1)

---

linux-cachyos-bmq/.SRCINFO
linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/.SRCINFO
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/.SRCINFO
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/.SRCINFO
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-rt-bore/.SRCINFO
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-server/.SRCINFO
linux-cachyos-server/PKGBUILD
linux-cachyos/.SRCINFO
linux-cachyos/PKGBUILD

Our installer appends tries to append crc32c_intel if an Intel chip is found on the system. This obviously fails in 6.14 because that module doesn't exist anymore, so add this alias as a hotfix before new ISOs are released.

stable: Hotfix for crc32-intel module

---

linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

Add distributed ThinLTO build support for the Linux kernel. This new mode offers several advantages: (1) Increased flexibility in handling user-specified build options. (2) Improved user-friendliness for developers. (3) Greater convenience for integrating with objtool and livepatch.
Note that "distributed" in this context refers to a term that differentiates in-process ThinLTO builds by invoking backend compilation through the linker, not necessarily building in distributed environments.
Depends on dfd4c69f9f12f8fdd68e08cdba250e37cefc93ce so merge this when 6.15rc4 is released
Link: https://lore.kernel.org/20250420010214.1963979-1-xur@google.com/

linux-cachyos-rc: Add support for Distributed ThinLTO

---

README.md

Reorganize content with better hierarchy, enhance installation instructions, improve feature categorization, and fix formatting inconsistencies for better user experience.

README: Refactor README and improve layout

---

linux-cachyos-bmq/PKGBUILD
linux-cachyos-bore/PKGBUILD
linux-cachyos-deckify/PKGBUILD
linux-cachyos-eevdf/PKGBUILD
linux-cachyos-hardened/PKGBUILD
linux-cachyos-lts/PKGBUILD
linux-cachyos-rc/PKGBUILD
linux-cachyos-rt-bore/PKGBUILD
linux-cachyos-server/PKGBUILD
linux-cachyos/PKGBUILD

After re-reading kernel Makefiles more deeply, I realized the public key filename is actually hardcoded and not derived from the private key, so we should do the same
Further, this makes the key routine more robust, as it does take absolute paths, which the current method did not support

Make kernel module signing more robust
